/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AirAmbulenceRole;

import Business.EcoSystem;
import java.awt.CardLayout;
import javax.swing.JPanel;
import Business.WorkQueue.DirtributionWorkRequest;
import Business.WorkQueue.OrganReportDocToHos;
import Business.WorkQueue.OrganRequestHosToUNOS;
import Business.WorkQueue.OrganRequestDocToHos;
import Business.WorkQueue.OrganReportHosToUNOS;
import Business.WorkQueue.ArtificialOrganRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.Component;
import javax.swing.JOptionPane;

/**
 *
 * @author wency
 */
public class ProcessJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    EcoSystem system;
    DirtributionWorkRequest request;
    OrganRequestDocToHos ordh;
    DirtributionWorkRequest dis;
    OrganRequestHosToUNOS htu;
    OrganReportDocToHos report;
    OrganReportHosToUNOS hs;
    ArtificialOrganRequest ao;
    /**
     * Creates new form ProcessJPanel
     */
    public ProcessJPanel(JPanel userProcessContainer,DirtributionWorkRequest request,OrganRequestDocToHos ordh,DirtributionWorkRequest dis,OrganRequestHosToUNOS htu,OrganReportDocToHos report,OrganReportHosToUNOS hs,ArtificialOrganRequest ao) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.ordh = ordh;
        this.dis = dis;
        this.htu = htu;
        this.report = report;
        this.hs = hs;
        this.ao = ao;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        back = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        Finished = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMonthTextField = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jDateTextField = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        finishtxt = new javax.swing.JTextField();

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        back.setText("back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel3.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 90, -1));

        submit.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        submit.setText("submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel3.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, 90, -1));

        jTextField1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 121, -1));

        Finished.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Finished.setText("Finished");
        Finished.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinishedActionPerformed(evt);
            }
        });
        jPanel3.add(Finished, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 270, 90, -1));

        jPanel1.setBackground(new java.awt.Color(15, 58, 59));
        jPanel1.setMaximumSize(new java.awt.Dimension(230, 1080));
        jPanel1.setMinimumSize(new java.awt.Dimension(230, 1080));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Air Amubulance");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 150, 10));

        jPanel4.setBackground(new java.awt.Color(7, 79, 80));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("    Manage Organization");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu.png"))); // NOI18N
        jLabel12.setText("    Process");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 180, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 230, 40));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 1080));

        jPanel10.setBackground(new java.awt.Color(37, 155, 156));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("/System/AirAmbulence");
        jPanel10.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Process");
        jPanel10.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-process.png"))); // NOI18N
        jPanel10.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 60, 70));

        jPanel3.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 850, 70));

        jLabel2.setText("Completed Date:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, -1, -1));

        jMonthTextField.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jMonthTextField.setText("MM");
        jPanel3.add(jMonthTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 40, -1));

        jLabel26.setText("/");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 10, 30));

        jDateTextField.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jDateTextField.setText("DD");
        jPanel3.add(jDateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 40, -1));

        jLabel25.setText("/");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 10, 40));

        finishtxt.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        finishtxt.setText("YYYY");
        jPanel3.add(finishtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, 50, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 753, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        AirAmbulenceWorkAreaJPanel dwjp = (AirAmbulenceWorkAreaJPanel) component;
        dwjp.populate();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:

        if (jTextField1.getText().isEmpty()) {
            JOptionPane.showMessageDialog((this), "Please enter all command field");
            return;
        }
        JOptionPane.showMessageDialog((this), "Submitted Successfully!", "Warning", JOptionPane.INFORMATION_MESSAGE);
        String status = jTextField1.getText();
        System.out.println("comeon"+report);
        report.setStatus(status);
        request.setStatus(status);
        ordh.setStatus(status);
        htu.setStatus(status);
        dis.setStatus(status);
        ao.setStatus(status);
        //JOptionPane.showMessageDialog((this), "Successfully Submitted", "Warning", JOptionPane.INFORMATION_MESSAGE);

        //        OrganRequestHosToUNOS re = (OrganRequestHosToUNOS)reqe;
        //        OrganReportDocToHos req = (OrganReportDocToHos)reqe;
        //        re.setStatus(status);
        //        req.setStatus(status);
    }//GEN-LAST:event_submitActionPerformed

    private void FinishedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinishedActionPerformed
        // TODO add your handling code here:
        
        String cd = finishtxt.getText();
        ordh.setCompletedDate(cd);
        ordh.setResult("finished");
        ordh.setStatus("finished");
        request.setCompletedDate(cd);
        request.setTestResult("finished");
        request.setStatus("finished");
        report.setStatus(cd);
        dis.setCompletedDate(cd);
        dis.setStatus("finished");
        dis.setTestResult("finished");
        htu.setCompletedDate(cd);
        htu.setTestResult("finished");
        htu.setStatus("finished");
        ao.setCompletedDate(cd);
        ao.setStatus("finished");
        
    }//GEN-LAST:event_FinishedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Finished;
    private javax.swing.JButton back;
    private javax.swing.JTextField finishtxt;
    private javax.swing.JTextField jDateTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jMonthTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
